### ISSUE TITLE
User Stories/MVP

### ISSUE THREAD

**Issue by richjimdev** [richjimdev/201-final-project#3]
[User Stories Google Doc](https://docs.google.com/document/d/1imZGrnCsBj0mdbAdfwXHu33cbiAb4oWADsP5kkRz9rY/edit?usp=sharing)

- [x] Discuss user stories
- [x] Finalize user stories

**Comment by mtncrawler** [comment]
Typed up User Stories and MVP in the same doc. These are open for discussion and/or modifications!
